### ISSUE TITLE
Add spacing between the -/+ buttons

### ISSUE THREAD

**Issue by ellieb** [ellieb/VICTORIA#1]
It would be nice to have some padding between the label, the decrement, and the increment buttons on the sliders.

[Those buttons](https://github.com/ellieb/VICTORIA/files/8202578/Screen.Shot.2022-03-07.at.22.49.34.pdf)

**Comment by HritikR** [comment]
Hi @ellieb, Can I work on this?

**Comment by ellieb** [comment]
Hi @HritikR! Sorry for the delay, I just saw this. Thanks for jumping in and making a PR! I'll take a look.
